---
- name: Workstation deployment
  hosts: all
  vars_files:
    - config.yml
    - secrets.yml
    - packages.yml
  tasks:
  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install workstation packages
    become: true
    community.general.pacman:
      name: "{{ packages }}"
      state: latest

  - name: Install aur packages
    become: yes
    become_user: aur_builder
    kewlfft.aur.aur:
      use: yay
      name: "{{ aur_packages }}"

  - name: Configure flathub remote
    become: true
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system
  
  - name: Install flatpaks
    become: true
    community.general.flatpak:
      name: "{{ flatpaks }}"
      state: present
  
  - name: Install python packages
    community.general.pipx:
      name: "{{ item }}"
    loop: "{{ pips }}"

  - name: Configure PAM for Yubikey
    become: true
    ansible.builtin.copy:
      src: files/common-u2f
      dest: /etc/pam.d/common-u2f
  
  - name: Add Yubikey as auth option for sudo
    become: true
    ansible.builtin.lineinfile:
      path: /etc/pam.d/sudo
      insertafter: '#%PAM-1.0'
      line: 'auth include common-u2f'
  
  - name: Install udev rules
    become: true
    ansible.builtin.copy:
      src: files/70-input.rules
      dest: /etc/udev/rules.d/70-input.rules
      mode: u=rw,g=r,o=r
  
  - name: Install udev rules
    become: true
    ansible.builtin.copy:
      src: files/50-usb-power-save.rules
      dest: /etc/udev/rules.d/50-usb-power-save.rules
      mode: u=rw,g=r,o=r
  
  - name: Reload udev rules
    become: true
    ansible.builtin.command: udevadm control --reload-rules
  
  - name: Configure user
    become: true
    ansible.builtin.user:
      name: "{{ user.name }}"
      comment: "{{ user.full_name }}"
      create_home: True
      shell: /usr/bin/zsh
      state: present
  
  - name: Create application directory (1/2)
    ansible.builtin.file:
      path: ${HOME}/.local/share/applications
      state: directory
      mode: '0755'
  
  - name: Create application directory (2/2)
    ansible.builtin.file:
      path: ${HOME}/.local/share/flatpak/exports/share/applications
      state: directory
      mode: '0755'

  - name: Update list of installed applications (1/2)
    ansible.builtin.command: update-desktop-database ${HOME}/.local/share/applications
  
  - name: Update list of installed applications (2/2)
    ansible.builtin.command: update-desktop-database ${HOME}/.local/share/flatpak/exports/share/applications

  - name: Clone dotfiles
    ansible.builtin.git:
      repo: https://github.com/tommoyer/dotfiles.git
      dest: ${HOME}/.dotfiles

  - name: Remove existing .ssh directory
    ansible.builtin.file:
      path: ${HOME}/.ssh
      state: absent
      
  - name: Stow dotfiles
    stow:
      state: latest
      package: '{{ item }}'
      dir: "${HOME}/.dotfiles"
      target: '$HOME'
    loop: "{{ dotfiles }}"
    
  - name: Post-Ansible finish script
    ansible.builtin.template:
      src: templates/finish-setup.sh.j2
      dest: ${HOME}/finish-setup.sh
      mode: u=rwx,g=r,o=r

  - name: Setup .local_profile
    ansible.builtin.template:
      src: templates/local_profile.j2
      dest: ${HOME}/.local_profile
      mode: u=rwx,g=r,o=r

  - name: Setup .gitconfig.gh
    ansible.builtin.template:
      src: templates/gitconfig.gh.j2
      dest: ${HOME}/.gitconfig.gh
      mode: u=rwx,g=r,o=r
    
  - name: Copy default keyboard settings
    become: true
    ansible.builtin.copy:
      src: files/keyboard
      dest: /etc/default/keyboard
      mode: u=rw,g=r,o=r

