---
- name: Workstation deployment
  hosts: all
  vars_files:
    - config.yml
    - packages.yml
    - secrets.yml
  
  tasks:
  - name: Create the `aur_builder` user
    become: true
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel
      system: true

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: true
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install workstation packages
    become: true
    community.general.pacman:
      name: "{{ packages }}"
      state: latest

  - name: Install aur packages
    become: true
    become_user: aur_builder
    kewlfft.aur.aur:
      use: yay
      name: "{{ aur_packages }}"
  
  - name: Install python packages
    community.general.pipx:
      name: "{{ item }}"
    loop: "{{ pips }}"

  - name: Configure PAM for Yubikey
    become: true
    ansible.builtin.copy:
      src: files/common-u2f
      dest: /etc/pam.d/common-u2f
  
  - name: Add Yubikey as auth option for sudo
    become: true
    ansible.builtin.lineinfile:
      path: /etc/pam.d/sudo
      insertafter: '#%PAM-1.0'
      line: 'auth include common-u2f'
  
  - name: Install udev rules
    become: true
    ansible.builtin.copy:
      src: files/70-input.rules
      dest: /etc/udev/rules.d/70-input.rules
      mode: u=rw,g=r,o=r
  
  - name: Install udev rules
    become: true
    ansible.builtin.copy:
      src: files/50-usb-power-save.rules
      dest: /etc/udev/rules.d/50-usb-power-save.rules
      mode: u=rw,g=r,o=r
  
  - name: Reload udev rules
    become: true
    ansible.builtin.command: udevadm control --reload-rules
  
  - name: Create application directory (1/2)
    ansible.builtin.file:
      path: ${HOME}/.local/share/applications
      state: directory
      mode: '0755'
  
  - name: Create application directory (2/2)
    ansible.builtin.file:
      path: ${HOME}/.local/share/flatpak/exports/share/applications
      state: directory
      mode: '0755'

  - name: Update list of installed applications (1/2)
    ansible.builtin.command: update-desktop-database ${HOME}/.local/share/applications
  
  - name: Update list of installed applications (2/2)
    ansible.builtin.command: update-desktop-database ${HOME}/.local/share/flatpak/exports/share/applications

  - name: Check if /etc/u2f_mappings exists
    ansible.builtin.stat:
      path: /etc/u2f_mappings
    register: u2f_mappings_file

  - name: Post-Ansible finish script
    ansible.builtin.copy:
      src: files/finish-setup.sh
      dest: ${HOME}/finish-setup.sh
      mode: u=rwx,g=r,o=r
    when: not u2f_mappings_file.stat.exists

  - name: Copy default keyboard settings
    become: true
    ansible.builtin.copy:
      src: files/keyboard
      dest: /etc/default/keyboard
      mode: u=rw,g=r,o=r

  - name: Append "splash quiet" to /etc/kernel/cmdline if not already present
    become: true
    ansible.builtin.lineinfile:
      path: /etc/kernel/cmdline
      # This regexp matches the entire line (captured in \1)
      # only if it does not already end with "splash quiet".
      regexp: '^(.*\S)(?<!splash quiet)$'
      # If the regexp matches, it replaces the line with its original content (\1)
      # followed by " splash quiet".
      line: '\1 splash quiet'
      backrefs: yes
      state: present # Ensures the line exists and is modified if regexp matches
      # Create the file if it does not exist (optional, remove if not desired)
      # create: yes
      # mode: '0644' # Set permissions if creating the file
  
  - name: Find .conf files in /efi/loader/entries
    become: true
    ansible.builtin.find:
      paths: /efi/loader/entries/
      patterns: "*.conf"
      recurse: no  # Entries are typically not in subdirectories
    register: loader_entries_found

  - name: Append "splash quiet" to options line in relevant bootloader entries
    become: true
    ansible.builtin.lineinfile:
      path: "{{ item.path }}"
      # This regexp matches a line starting with "options "
      # and captures the entire line in \1, but only if the line
      # does NOT already contain the whole word "splash quiet".
      regexp: '^(options\s+(?:(?!.*\bsplash quiet\b).)*)$'
      # If the regexp matches, the line is replaced by its original content (\1)
      # followed by " splash quiet".
      line: '\1 splash quiet'
      backrefs: yes
      state: present # Ensures the line is present (modifies if regexp matches)
    loop: "{{ loader_entries_found.files }}"
    when:
      # Ensure we are processing actual files found by the find module
      - item.path is defined
      # Exclude files ending with -fallback.conf
      - not item.path.endswith('-fallback.conf')

  - name: Enable libvirtd.service
    become: true
    ansible.builtin.systemd:
      name: libvirtd.service
      enabled: true
      state: started

  - name: Enable docker.service
    become: true
    ansible.builtin.systemd:
      name: docker.service
      enabled: true
      state: started

  - name: Enable incus.service
    become: true
    ansible.builtin.systemd:
      name: incus.service
      enabled: true
      state: started
      
  - name: Enable libvirtd.socket
    become: true
    ansible.builtin.systemd:
      name: libvirtd.socket
      enabled: true
      state: started

  - name: Set incusbr0 to trusted
    become: true
    ansible.posix.firewalld:
      interface: incusbr0
      zone: trusted
      state: enabled
      permanent: true
      immediate: true

  - name: List incus storage pools
    become: true
    ansible.builtin.command: /usr/bin/incus storage list -f csv -c n
    register: incus_storage_list

  - name: Run incus admin init with preseed
    become: true
    ansible.builtin.command: /usr/bin/incus admin init --preseed files/incus-preseed.yaml
    when: "'default' not in incus_storage_list.stdout"

  - name: Enable systemd-resolved
    become: true
    ansible.builtin.systemd:
      name: systemd-resolved
      enabled: true
      state: started

  - name: Set up systemd-resolved symlink to resolv.conf
    become: true
    ansible.builtin.file:
      src: /run/systemd/resolve/stub-resolv.conf
      dest: /etc/resolv.conf
      state: link
      force: true

  - name: Copy incus-dns-incusbr0.service to systemd directory
    become: true
    ansible.builtin.copy:
      src: files/incus-dns-incusbr0.service
      dest: /etc/systemd/system/incus-dns-incusbr0.service
      owner: root
      group: root
      mode: '0644'

  - name: Reload systemd daemon to recognize new service
    become: true
    ansible.builtin.systemd:
      daemon_reload: yes

  - name: Enable and start incus-dns-incusbr0.service
    become: true
    ansible.builtin.systemd:
      name: incus-dns-incusbr0.service
      enabled: yes
      state: started

  - name: Enable bluetooth.service
    become: true
    ansible.builtin.systemd:
      name: bluetooth.service
      enabled: true
      state: started

  - name: Ensure docker directory exists
    become: true
    ansible.builtin.file:
      path: "/etc/docker/"
      state: directory
      mode: '0755'

  - name: Copy the docker daemon.json file
    become: true
    ansible.builtin.copy:
      src: files/daemon.json
      dest: /etc/docker/daemon.json
      owner: root
      group: root
      mode: '0644'

  - name: Configure user
    become: true
    ansible.builtin.user:
      name: "{{ user.name }}"
      comment: "{{ user.full_name }}"
      create_home: True
      shell: /usr/bin/bash
      state: present
      append: true
      groups:
        - wheel
        - libvirt
        - docker
        - incus-admin

  - name: Set keyboard options using localectl
    become: true
    ansible.builtin.command: '/usr/bin/localectl set-x11-keymap us pc105 "" ctrl:nocaps,shift:both_capslock_cancel'
    args:
      creates: /etc/X11/xorg.conf.d/00-keyboard.conf

  - name: Set subuid and subgid ranges for root for incus unprivileged containers
    become: true
    ansible.builtin.command: '/usr/bin/usermod -v 1000000-1000999999 -w 1000000-1000999999 root'

- name: Workstation deployment (gcloud cli)
  hosts: all
  become: true
  roles:
    - role: google.cloud.gcloud
      gcloud_install_type: archive

- name: Deploy dotfiles
  hosts: all
  vars_files:
    - config.yml
    - packages.yml
    - secrets.yml
  tasks:
  # Create necessary directories
    - name: Ensure home directories exist
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - .config
        - .local
        - .local/share
        - .ssh
        - .gnupg
        - Applications
        - .config/neomutt
        - .config/neomutt/accounts
        - .config/neomutt/gmail/cache
        - .config/neomutt/gmail/certificates
        - .config/neomutt/gmail/headers
        - .config/neomutt/terrablue/cache
        - .config/neomutt/terrablue/certificates
        - .config/neomutt/terrablue/headers
        - .config/neomutt/uncc/cache
        - .config/neomutt/uncc/certificates
        - .config/neomutt/uncc/headers
        - .config/zsh-completions

    # Deploy template files
    - name: Deploy .gitconfig from template
      ansible.builtin.template:
        src: templates/gitconfig.j2
        dest: "{{ lookup('env', 'HOME') }}/.gitconfig"
        mode: '0644'

    - name: Deploy .local_profile from template
      ansible.builtin.template:
        src: templates/local_profile.j2
        dest: "{{ lookup('env', 'HOME') }}/.local_profile"
        mode: '0644'

    - name: Deploy user ansible.cfg from template
      ansible.builtin.template:
        src: templates/ansible_user.cfg.j2
        dest: "{{ lookup('env', 'HOME') }}/.ansible.cfg"
        mode: '0644'

    - name: Deploy streamdeck_ui.json from template
      ansible.builtin.template:
        src: templates/streamdeck_ui.json.j2
        dest: "{{ lookup('env', 'HOME') }}/.streamdeck_ui.json"
        mode: '0644'

    - name: Deploy disable-pihole.sh script
      ansible.builtin.template:
        src: templates/disable-pihole.sh.j2
        dest: "{{ lookup('env', 'HOME') }}/Applications/disable-pihole.sh"
        mode: '0755'

    - name: Deploy neomutt account configurations
      ansible.builtin.template:
        src: "templates/neomutt_accounts/{{ item }}.j2"
        dest: "{{ lookup('env', 'HOME') }}/.config/neomutt/accounts/{{ item }}"
        mode: '0644'
      loop:
        - gmail
        - terrablue
        - uncc

    # Deploy symlinks
    - name: Deploy symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        # Static dotfiles
        - src: "{{ playbook_dir }}/files/aspell.en.prepl"
          dest: "{{ lookup('env', 'HOME') }}/.aspell.en.prepl"
        - src: "{{ playbook_dir }}/files/aspell.en.pws"
          dest: "{{ lookup('env', 'HOME') }}/.aspell.en.pws"
        - src: "{{ playbook_dir }}/files/gitignore"
          dest: "{{ lookup('env', 'HOME') }}/.gitignore"
        - src: "{{ playbook_dir }}/files/latexmkrc"
          dest: "{{ lookup('env', 'HOME') }}/.latexmkrc"
        - src: "{{ playbook_dir }}/files/mrconfig"
          dest: "{{ lookup('env', 'HOME') }}/.mrconfig"
        - src: "{{ playbook_dir }}/files/mrtrust"
          dest: "{{ lookup('env', 'HOME') }}/.mrtrust"
        - src: "{{ playbook_dir }}/files/sops.yaml"
          dest: "{{ lookup('env', 'HOME') }}/.sops.yaml"
        - src: "{{ playbook_dir }}/files/tmux.conf"
          dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
        - src: "{{ playbook_dir }}/files/zimrc"
          dest: "{{ lookup('env', 'HOME') }}/.zimrc"
        - src: "{{ playbook_dir }}/files/zshenv"
          dest: "{{ lookup('env', 'HOME') }}/.zshenv"
        - src: "{{ playbook_dir }}/files/zshrc"
          dest: "{{ lookup('env', 'HOME') }}/.zshrc"
        # .config directories and files
        - src: "{{ playbook_dir }}/files/config/fontconfig"
          dest: "{{ lookup('env', 'HOME') }}/.config/fontconfig"
        - src: "{{ playbook_dir }}/files/config/mr"
          dest: "{{ lookup('env', 'HOME') }}/.config/mr"
        # Fonts
        - src: "{{ playbook_dir }}/files/local/share/fonts"
          dest: "{{ lookup('env', 'HOME') }}/.local/share/fonts"
        # SSH files
        - src: "{{ playbook_dir }}/files/ssh/config"
          dest: "{{ lookup('env', 'HOME') }}/.ssh/config"
        - src: "{{ playbook_dir }}/files/ssh/authorized_keys"
          dest: "{{ lookup('env', 'HOME') }}/.ssh/authorized_keys"
        - src: "{{ playbook_dir }}/files/ssh/id_rsa.pub"
          dest: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa.pub"
        # GnuPG files
        - src: "{{ playbook_dir }}/files/gnupg/gpg.conf"
          dest: "{{ lookup('env', 'HOME') }}/.gnupg/gpg.conf"
        - src: "{{ playbook_dir }}/files/gnupg/gpg-agent.conf"
          dest: "{{ lookup('env', 'HOME') }}/.gnupg/gpg-agent.conf"
        # Application scripts
        - src: "{{ playbook_dir }}/files/Applications/newproj"
          dest: "{{ lookup('env', 'HOME') }}/Applications/newproj"
        - src: "{{ playbook_dir }}/files/Applications/incus-vm-iso.sh"
          dest: "{{ lookup('env', 'HOME') }}/Applications/incus-vm-iso.sh"
        # Media directories
        - src: "{{ playbook_dir }}/files/Music"
          dest: "{{ lookup('env', 'HOME') }}/Music"
        - src: "{{ playbook_dir }}/files/Pictures"
          dest: "{{ lookup('env', 'HOME') }}/Pictures"

    # Deploy GnuPG files
    - name: Ensure .gnupg directory has correct permissions
      ansible.builtin.file:
        path: "{{ lookup('env', 'HOME') }}/.gnupg"
        state: directory
        mode: '0700'

    - name: Refresh font cache
      ansible.builtin.command: fc-cache -fv
      changed_when: false
      ignore_errors: yes
