---
- name: Workstation deployment
  hosts: all
  vars_files:
    - config.yml
    - secrets.yml
    - packages.yml
  tasks:
  - name: Create the `aur_builder` user
    become: yes
    ansible.builtin.user:
      name: aur_builder
      create_home: yes
      group: wheel

  - name: Allow the `aur_builder` user to run `sudo pacman` without a password
    become: yes
    ansible.builtin.lineinfile:
      path: /etc/sudoers.d/11-install-aur_builder
      line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: yes
      mode: 0644
      validate: 'visudo -cf %s'

  - name: Install workstation packages
    become: true
    community.general.pacman:
      name: "{{ packages }}"
      state: latest

  - name: Install aur packages
    become: yes
    become_user: aur_builder
    kewlfft.aur.aur:
      use: yay
      name: "{{ aur_packages }}"

  - name: Configure flathub remote
    become: true
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
      method: system
  
  - name: Install flatpaks
    become: true
    community.general.flatpak:
      name: "{{ flatpaks }}"
      state: present
  
  - name: Install python packages
    community.general.pipx:
      name: "{{ item }}"
    loop: "{{ pips }}"

  - name: Configure PAM for Yubikey
    become: true
    ansible.builtin.copy:
      src: files/common-u2f
      dest: /etc/pam.d/common-u2f
  
  - name: Add Yubikey as auth option for sudo
    become: true
    ansible.builtin.lineinfile:
      path: /etc/pam.d/sudo
      insertafter: '#%PAM-1.0'
      line: 'auth include common-u2f'
  
  - name: Install udev rules
    become: true
    ansible.builtin.copy:
      src: files/70-input.rules
      dest: /etc/udev/rules.d/70-input.rules
      mode: u=rw,g=r,o=r
  
  - name: Install udev rules
    become: true
    ansible.builtin.copy:
      src: files/50-usb-power-save.rules
      dest: /etc/udev/rules.d/50-usb-power-save.rules
      mode: u=rw,g=r,o=r
  
  - name: Reload udev rules
    become: true
    ansible.builtin.command: udevadm control --reload-rules
  
  - name: Configure user
    become: true
    ansible.builtin.user:
      name: "{{ user.name }}"
      comment: "{{ user.full_name }}"
      create_home: True
      shell: /usr/bin/zsh
      state: present
  
  - name: Create application directory (1/2)
    ansible.builtin.file:
      path: ${HOME}/.local/share/applications
      state: directory
      mode: '0755'
  
  - name: Create application directory (2/2)
    ansible.builtin.file:
      path: ${HOME}/.local/share/flatpak/exports/share/applications
      state: directory
      mode: '0755'

  - name: Update list of installed applications (1/2)
    ansible.builtin.command: update-desktop-database ${HOME}/.local/share/applications
  
  - name: Update list of installed applications (2/2)
    ansible.builtin.command: update-desktop-database ${HOME}/.local/share/flatpak/exports/share/applications

  - name: Clone dotfiles
    ansible.builtin.git:
      repo: https://github.com/tommoyer/dotfiles.git
      dest: ${HOME}/.dotfiles

  - name: Remove existing .ssh directory
    ansible.builtin.file:
      path: ${HOME}/.ssh
      state: absent
      
  - name: Stow dotfiles
    stow:
      state: latest
      package: '{{ item }}'
      dir: "${HOME}/.dotfiles"
      target: '$HOME'
    loop: "{{ dotfiles }}"
    
  - name: Post-Ansible finish script
    ansible.builtin.template:
      src: templates/finish-setup.sh.j2
      dest: ${HOME}/finish-setup.sh
      mode: u=rwx,g=r,o=r

  - name: Setup .local_profile
    ansible.builtin.template:
      src: templates/local_profile.j2
      dest: ${HOME}/.local_profile
      mode: u=rwx,g=r,o=r

  - name: Setup .gitconfig.gh
    ansible.builtin.template:
      src: templates/gitconfig.gh.j2
      dest: ${HOME}/.gitconfig.gh
      mode: u=rwx,g=r,o=r
    
  - name: Copy default keyboard settings
    become: true
    ansible.builtin.copy:
      src: files/keyboard
      dest: /etc/default/keyboard
      mode: u=rw,g=r,o=r

  - name: Append "splash quiet" to /etc/kernel/cmdline if not already present
    become: true
    ansible.builtin.lineinfile:
      path: /etc/kernel/cmdline
      # This regexp matches the entire line (captured in \1)
      # only if it does not already end with "splash quiet".
      regexp: '^(.*\S)(?<!splash quiet)$'
      # If the regexp matches, it replaces the line with its original content (\1)
      # followed by " splash quiet".
      line: '\1 splash quiet'
      backrefs: yes
      state: present # Ensures the line exists and is modified if regexp matches
      # Create the file if it does not exist (optional, remove if not desired)
      # create: yes
      # mode: '0644' # Set permissions if creating the file
  
  - name: Find .conf files in /efi/loader/entries
    become: true
    ansible.builtin.find:
      paths: /efi/loader/entries/
      patterns: "*.conf"
      recurse: no  # Entries are typically not in subdirectories
    register: loader_entries_found

  - name: Append "splash quiet" to options line in relevant bootloader entries
    become: true
    ansible.builtin.lineinfile:
      path: "{{ item.path }}"
      # This regexp matches a line starting with "options "
      # and captures the entire line in \1, but only if the line
      # does NOT already contain the whole word "splash quiet".
      regexp: '^(options\s+(?:(?!.*\bsplash quiet\b).)*)$'
      # If the regexp matches, the line is replaced by its original content (\1)
      # followed by " splash quiet".
      line: '\1 splash quiet'
      backrefs: yes
      state: present # Ensures the line is present (modifies if regexp matches)
    loop: "{{ loader_entries_found.files }}"
    when:
      # Ensure we are processing actual files found by the find module
      - item.path is defined
      # Exclude files ending with -fallback.conf
      - not item.path.endswith('-fallback.conf')

  - name: Copy incus.service overrides
    ansible.builtin.copy:
      src: files/override.conf
      dest: /etc/systemd/system/incus.service.d/override.conf
      mode: '0644'
      owner: root
      group: root
